### ISSUE TITLE
Error: $http:badjsonp

### ISSUE THREAD

**Issue by switch13** [JohnnyTheTank/angular-tumblr-api-factory#2]
[$http:badjsonp] Illegal use of JSON_CALLBACK in url

Looks like the latest version of AngularJS does not allow the callback param to be JSON_CALLBACK anymore.

https://docs.angularjs.org/error/$http/badjsonp

I can see where it's happening on line 80, just don't know how to fix it.

**Comment by mahowa** [comment]
Change
` var tumblrSearchData = {
                object: {
                    api_key:_params.api_key || undefined,
                    callback: "JSON_CALLBACK"
                },
                url: "",
            };
`

To

` var tumblrSearchData = {
                object: {
                    api_key:_params.api_key || undefined,
                },
                url: "",
            };
`

by removing 
`callback: "JSON_CALLBACK"`
from the object inside angular-tumbr-api-factory.js

**Comment by JohnnyTheTank** [comment]
or just use angular 1.5
